apiVersion: batch/v1
kind: Job
metadata:
  name: sync
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-options: Prune=true
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "10"]
      restartPolicy: Never
  backoffLimit: 0
